# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lab3basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='basket_name',
            field=models.CharField(default='basket', max_length=123),
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='files',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
