# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3basket', '0004_auto_20170927_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='path',
            field=models.CharField(default='migrate', max_length=123, verbose_name='basket path'),
        ),
    ]
