# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3basket', '0006_auto_20170927_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketmodel',
            name='path_inform',
            field=models.CharField(default='/home/student/information.json', max_length=123, verbose_name='information path'),
        ),
    ]
