# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3basket', '0007_basketmodel_path_inform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='path_inform',
        ),
    ]
